version: '2.1'
services:
  yapi:
    image: sunhao-java/yapi
    container_name: yapi
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./yapi.log:/home/vendors/log
    env_file:
      - .env
  